version: "3.8"


services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: "1.21.1" 
      MEMORY: "6G"
      ENABLE_WHITELIST: "FALSE"
      OVERRIDE_SERVER_PROPERTIES: "FALSE"
      SERVER_NAME: "MODDED SERVER"
      MODE: "SURVIVAL"
      ONLINE_MODE: "TRUE"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ALLOW_NETHER: "TRUE"
      OVERRIDE_ICON: "TRUE"
      ICON: "https://cdn.vox-cdn.com/thumbor/8KxJUDwQsz5Qy-_HzZjtCTRR5PU=/0x164:1440x884/fit-in/1200x600/cdn.vox-cdn.com/uploads/chorus_asset/file/22310830/NmJgg.jpg"
    tty: true
    stdin_open: true
    
    ports:
      - 25565:25565
    volumes:
      - E:\Running-Minecraft-In-Production-main\Modding-Minecraft-Docker\mc-data:/data
      - E:\Running-Minecraft-In-Production-main\Modding-Minecraft-Docker\mods:/mods
    restart: on-failure:3